version: '3.8'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: larabrute_php
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../:/var/www
    nginx:
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        container_name: larabrute_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ../:/var/www
networks:
    default:
        name: mysql
        external: true
