name: Publish Docker image
on:
  pull_request:
    branches: [master]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup .env from secrets
        run: echo "${{ secrets.PROD_DOTENV }}" | base64 -d > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create network to allow building compose
        run: docker network create mysql

      - name: Build images
        run: docker-compose up --build

      - name: Push images to Docker Hub
        run: docker-compose --push
